insert into public.brand_seeds (slug, name, category, aliases)
values
	('courier-generic', 'Courier', 'generic', ARRAY['delivery service', 'parcel service', 'courier']),
	('retail-generic', 'Retailer', 'generic', ARRAY['store', 'marketplace', 'order service']),
	('telecom-generic', 'Carrier', 'generic', ARRAY['mobile carrier', 'cell provider', 'phone company']),
	('tech-generic', 'Tech Platform', 'generic', ARRAY['online account']),
	('government-generic', 'Government', 'generic', ARRAY['tax department', 'service center']),
	('banking-generic', 'Bank', 'generic', ARRAY['financial institution']),
	('canada-post', 'Canada Post', 'courier', ARRAY['poste canada']),
	('purolator', 'Purolator', 'courier', ARRAY['puro']),
	('fedex', 'FedEx', 'courier', '{}'),
	('ups', 'UPS', 'courier', ARRAY['myups', 'united parcel service']),
	('usps', 'USPS', 'courier', ARRAY['united states postal service', 'us postal service']),
	('dhl', 'DHL', 'courier', ARRAY['dhl express']),
	('cbsa', 'CBSA', 'government', ARRAY['canada border services agency', 'canadian customs']),
	('cra', 'CRA', 'government', ARRAY['canada revenue agency', 'revenue canada']),
	('service-canada', 'Service Canada', 'government', '{}'),
	('service-ontario', 'ServiceOntario', 'government', ARRAY['service ontario']),
	('ontario-transport', 'Ministry of Transportation Ontario', 'government', ARRAY['mto', 'ontario ministry of transportation', 'ontario transport']),
	('american-express', 'American Express', 'finance', ARRAY['amex']),
	('bmo', 'BMO', 'finance', ARRAY['bank of montreal']),
	('capital-one', 'Capital One', 'finance', ARRAY['cap1']),
	('cibc', 'CIBC', 'finance', ARRAY['canadian imperial bank of commerce', 'canadian imperial bank']),
	('interac', 'Interac', 'finance', ARRAY['interac e-transfer', 'etransfer', 'e-transfer']),
	('mastercard', 'Mastercard', 'finance', ARRAY['master card']),
	('paypal', 'PayPal', 'finance', ARRAY['pay pal']),
	('rbc', 'RBC', 'finance', ARRAY['royal bank', 'royal bank of canada']),
	('scotiabank', 'Scotiabank', 'finance', ARRAY['scotia', 'bank of nova scotia']),
	('td', 'TD', 'finance', ARRAY['td canada trust']),
	('visa', 'Visa', 'finance', ARRAY['visa secure']),
	('wealthsimple', 'Wealthsimple', 'finance', '{}'),
	('questrade', 'Questrade', 'finance', '{}'),
	('adobe', 'Adobe', 'tech', ARRAY['adobe sign', 'adobesign', 'adobe-sign']),
	('apple', 'Apple', 'tech', ARRAY['icloud', 'apple id', 'appleid']),
	('discord', 'Discord', 'tech', '{}'),
	('disney-plus', 'Disney+', 'tech', '{}'),
	('gmail', 'Gmail', 'tech', ARRAY['google mail']),
	('google', 'Google', 'tech', '{}'),
	('microsoft', 'Microsoft', 'tech', ARRAY['microsoft account']),
	('netflix', 'Netflix', 'tech', '{}'),
	('steam', 'Steam', 'tech', ARRAY['steam guard']),
	('whatsapp', 'WhatsApp', 'tech', '{}'),
	('bell', 'Bell', 'telecom', '{}'),
	('rogers', 'Rogers', 'telecom', ARRAY['rogers communications', 'rogers wireless']),
	('telus', 'TELUS', 'telecom', '{}'),
	('fido', 'Fido', 'telecom', ARRAY['fido solutions']),
	('koodo', 'Koodo', 'telecom', ARRAY['koodo mobile']),
	('freedom-mobile', 'Freedom Mobile', 'telecom', ARRAY['freedom mobile', 'freedom']),
	('virgin-plus', 'Virgin Plus', 'telecom', ARRAY['virgin mobile', 'virgin mobile canada']),
	('verizon', 'Verizon', 'telecom', ARRAY['verizon wireless']),
	('t-mobile', 'T-Mobile', 'telecom', ARRAY['tmobile', 't mobile']),
	('att', 'AT&T', 'telecom', ARRAY['at&t', 'att'])
on conflict (slug) do update
set
	name = excluded.name,
	category = excluded.category,
	aliases = excluded.aliases,
	updated_at = now();
